<?php
/**
 * @file
 * Provides field bases for fields defined by the Image module.
 */

/**
 * Implements hook_field_creator_base().
 */
function taxonomy_field_creator_base() {
  $fields = array();

   // Exported field_base: 'field_term_reference_proto'
  $fields['field_term_reference_proto'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_term_reference_proto',
    'foreign keys' => array(
      'tid' => array(
        'columns' => array(
          'tid' => 'tid',
        ),
        'table' => 'taxonomy_term_data',
      ),
    ),
    'indexes' => array(
      'tid' => array(
        0 => 'tid',
      ),
    ),
    'locked' => 0,
    'module' => 'taxonomy',
    'settings' => array(
      'allowed_values' => array(
        0 => array(
          'vocabulary' => 'tags',
          'parent' => 0,
        ),
      ),
    ),
    'translatable' => 0,
    'type' => 'taxonomy_term_reference',
  );

  return $fields;
}

/**
 * Implements hook_field_creator_instance().
 */
function taxonomy_field_creator_instance() {
  
  $field_instances = array();
  
  // Exported field_instance: 'node-proto-field_term_reference_proto'
  $field_instances['node-proto-field_term_reference_proto'] = array(
    'bundle' => 'proto',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_link',
        'weight' => 24,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_term_reference_proto',
    'label' => 'Term Reference',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 54,
    ),
  );
  
  return $field_instances;
}