<?php
/**
 * @file
 * Provides field bases for fields defined by the Image module.
 */

/**
 * Implements hook_field_creator_base().
 */
function image_field_creator_base() {
  $fields = array();

  // Exported field_base: 'field_image_proto'
  $field_bases['field_image_proto'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_image_proto',
    'foreign keys' => array(
      'fid' => array(
        'columns' => array(
          'fid' => 'fid',
        ),
        'table' => 'file_managed',
      ),
    ),
    'indexes' => array(
      'fid' => array(
        0 => 'fid',
      ),
    ),
    'locked' => 0,
    'module' => 'image',
    'settings' => array(
      'default_image' => 0,
      'uri_scheme' => 'public',
    ),
    'translatable' => 0,
    'type' => 'image',
  );

  return $fields;
}